### ISSUE TITLE
hopscotch_set::emplace doesn't work with MSVC compiler

### ISSUE THREAD

**Issue by olegator77** [Tessil/hopscotch-map#52] opened 2020-08-07 16:05 UTC
```
#include <iostream>
#include "hopscotch/hopscotch_set.h"

void test() {
	tsl::hopscotch_set<int> xx;
	xx.emplace(1);
	std::cout << "size after emplace:" << xx.size() << std::endl;
}

void test1() {
	tsl::hopscotch_set<int> xx;
	xx.insert(1);
	std::cout << "size after insert:" << xx.size() << std::endl;
}

int main(int argc, char* argv[]) {
	test();
	test1();
```

output:
```
size after emplace:0                                                                                                                                          
size after insert:1      
```
MSVC 2019 compiler

**Comment by Tessil** [comment] 2020-08-07 16:58
Hi,

That's quite surprising as the `emplace` method [delegates](https://github.com/Tessil/hopscotch-map/blob/master/include/tsl/hopscotch_hash.h#L909) its work to `insert` as it isn't really possible to construct the element in-place without first getting the hash of the inserted element in an open-addressing hash map (and is thus equivalent to an insert). A node-based one can directly create a new node in-place. The `try_emplace` method is more useful.

I tested it on MSVC 2015 and the example works fine, I need to try with MSVC 2019 but I suspect a bug in the compiler.

Thibaut

**Comment by Tessil** [comment] 2020-08-08 10:45
Hi,

It seems to be working with VS 2019. I also added it to the CI pipeline and added a test in a branch (commit 548f248ffcc8bbd368cea6861b2aafd00dad60d9) and the CI passes on all tests (see https://ci.appveyor.com/project/Tessil/hopscotch-map/builds/34551413).

Which revision of VS 2019 do you use? Could you try to update it?

Thibaut

**Comment by olegator77** [comment] 2020-08-08 12:27
Hi, 
Thank you for reaction.
It is possible, that this problem was caused by compiler flags in project, or some another environment specific. 
I'll check environment, and return with feedback bit later.

**Comment by Tessil** [comment] 2020-08-30 14:55
I'll close the issue for now as it seems the bug comes from the compiler and I wasn't able to reproduce it. Let me know if the problem persists with an updated version of MSVC 2019. I'll also be interested by the MSVC 2019 version that caused the bug to confirm the bug comes from there.

**Closed by Tessil** 2020-08-30 14:55 UTC
