### ISSUE TITLE
Warning: comparison 'unsigned int' <= 4294967295 is always true

### ISSUE THREAD

**Issue by dan-ryan** [Tessil/hopscotch-map#45] opened 2019-02-21 21:04 UTC
While compiling my code, I'm getting this warning.

`hopscotch_hash.h:1743:39:  warning: comparison 'unsigned int' <= 4294967295 is always true [-Wtautological-constant-compare]"`

**Comment by Tessil** [comment] 2019-02-21 21:49
Could you try the branch [fix_issue_45](https://github.com/Tessil/hopscotch-map/compare/fix_issue_45)?

Which version of Clang are you using? I can't reproduce the bug with my version even if compile in 32 bits.

**Comment by dan-ryan** [comment] 2019-02-21 22:15
Clang 8.2, I'll give your branch a try.

**Comment by dan-ryan** [comment] 2019-02-22 00:38
Looks like that branch did the trick.

**Comment by Tessil** [comment] 2019-02-24 13:34
I merged the change.

**Closed by Tessil** 2019-02-24 13:34 UTC
